// API Response Types based on openapi.json

export interface ApiResponse<T> {
  success: boolean
  data: T
}

export interface ApiListResponse<T> {
  success: boolean
  count: number
  data: T[]
}

export interface ApiError {
  error: string
  message: string
  statusCode: number
}

// Image Types
export interface Image {
  id: number
  uuid: string
  filename: string
  fileSize: number
  format: 'jpg' | 'jpeg' | 'png' | 'tif' | 'tiff'
  width: number
  height: number
  hash: string
  mimeType: string
  isCorrupted: boolean
  createdAt: string
  updatedAt: string
  deletedAt: string | null
  exifData?: ExifData
  presignedUrl?: string
}



export interface ExifExtra {
  whiteBalance?: number;
  flash?: number;
  exposureMode?: number;
  meteringMode?: number;
  colorSpace?: number;
  [key: string]: any;
}

export interface ExifData {
  // DO NOT INCLUDE: id, uuid - these are auto-generated by server

  cameraMake?: string | null;
  cameraModel?: string | null;
  lensModel?: string | null;

  artist?: string | null;
  copyright?: string | null;
  software?: string | null;

  iso?: number | null;

  shutterSpeed?: string | null;  // e.g., "1/250"
  aperture?: string | null;       // e.g., "f/2.8"
  focalLength?: string | null;    // e.g., "50mm"

  dateTaken?: string | null;      // ISO 8601 date string

  orientation?: number | null;    // 1-8 (EXIF orientation values)

  gpsLatitude?: string | null;    // decimal string
  gpsLongitude?: string | null;   // decimal string
  gpsAltitude?: string | null;    // decimal string

  extra?: ExifExtra | null;       // Additional metadata
}



export interface ImageStats {
  totalCount: number
  totalSize: number
  corruptedCount: number
  jpgCount: number
  pngCount: number
  tifCount: number
}

export interface HealthCheck {
  status: string
  timestamp: string
  database: string
}

// Request Types
export interface GetImagesParams {
  withExif?: boolean
}

export type UpdateImageExifRequest = Partial<ExifData>;







// FIXME 
export interface GetImagesByUUIDResponse {
  success: boolean
  data: Image[]
  count: number
  requested: number
}

export interface UploadImagesRequest {
  images: File[]
}

export interface DeleteImageResponse {
  success: boolean
  message: string
}



export interface UploadImagesResponse {
  success: boolean
  message: string
  data?: Image[]
}

export interface PreSignURLsResponse {
  success: boolean,
  data: {
    imageUrl: string;
    thumbnailUrl: string;
    objectName: string;
    bucketName: string;
    uuid: string;
  }[]

}


// Pagination Types
export interface PaginationMeta {
  nextCursor: string | null
  hasMore: boolean
  limit: number
}

export interface PagePaginationMeta {
  page: number
  pageSize: number
  totalItems: number
  totalPages: number
  hasNext: boolean
  hasPrev: boolean
}

export interface PaginatedImagesResponse {
  success: boolean
  count: number
  data: Image[]
  pagination: PaginationMeta
}

export interface GetPaginatedImagesParams {
  limit?: number
  cursor?: string
  collectionId?: number
  withExif?: boolean
  sortBy?: 'name' | 'size' | 'type' | 'updatedAt' | 'createdAt'
  sortOrder?: 'asc' | 'desc'
}


export interface GetPagePaginatedImagesResponse {
  success: boolean
  count: number
  data: Image[]
  pagination: PagePaginationMeta
}



export interface GetPagePaginatedImagesParams {
  page: number
  pageSize: number
  collectionId?: number
  withExif?: boolean
  sortBy?: 'name' | 'size' | 'type' | 'updatedAt' | 'createdAt'
  sortOrder?: 'asc' | 'desc'
}


// Sync System Types
export interface SyncOperation {
  id: number
  sequenceNumber: number
  operation: 'upload' | 'delete' | 'update' | 'replace' | 'batch_upload' | 'batch_delete'
  imageId: number | null
  imageUuid: string | null
  clientId: string
  groupOperationId: string | null
  metadata: Record<string, any>
  createdAt: string
}

export interface SyncOperationsResponse {
  success: boolean
  data: SyncOperation[]
  sync: {
    currentSequence: number
    requestedSince: number
    returnedCount: number
    hasMore: boolean
  }
}

export interface SyncStatusResponse {
  success: boolean
  data: {
    currentSequence: number
    clientLastSequence: number
    isInSync: boolean
    operationsBehind: number
  }
}

export interface SyncCurrentResponse {
  success: boolean
  data: {
    currentSequence: number
  }
}

export interface MyOperationsResponse {
  success: boolean
  data: SyncOperation[]
  count: number
}
